# Generated by Django 2.2.3 on 2019-08-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.TextField()),
                ('company', models.TextField()),
                ('job', models.TextField()),
                ('mobile', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FriendModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='PEN', max_length=3)),
                ('doctor', models.ManyToManyField(to='api.DoctorModel')),
                ('patient', models.ManyToManyField(to='api.PatientModel')),
            ],
        ),
    ]
